name: Alert - Prymal Shopify Low Inventory
run-name: ${{ github.actor }} - Shopify Low Inventory Alert 
on: 
  push:
    paths:
      - '**/alert/**'
      - '**/workflows/prymal_alert_shopify_low_inventory.yml'
  schedule:
    - cron: '0 11 * * *'  # Runs at 11 AM every day
jobs:
  prymal_alert_shopify_low_inventory:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo code
        uses: actions/checkout@v3
      - run: echo "${{ github.repository }} repository has been cloned to the runner. The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Set up Python env
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r extraction/requirements.txt
    
      - name: Generate Alert
        env: 
          AWS_ACCESS_KEY:  ${{ secrets.AWS_ACCESS_KEY }}
          AWS_ACCESS_SECRET: ${{ secrets.AWS_ACCESS_SECRET }}
        run: python alert/alert.py 

        

      - run: echo "Job status - ${{ job.status }}."
